// Generated by ResX, do not edit manually

type assets = {
  /** ResX Client Bundle */
  resXClient_js: string,

  /** `rescript-logo.svg` */
  rescript_logo_svg: string,

  /** `styles.css` */
  styles_css: string,
}

@module("./res-x-assets.js") external assets: assets = "assets"

@module("./res-x-static-routes.js") external staticAssetRoutes: Dict.t<Bun.routeHandlerObject> = "staticAssetRoutes"