// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Prompts from "@clack/prompts";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var Spinner = {};

var Log = {};

var Canceled = /* @__PURE__ */Caml_exceptions.create("ClackPrompts.Canceled");

async function resultOrRaise(promise) {
  var result = await promise;
  if (Prompts.isCancel(result)) {
    throw {
          RE_EXN_ID: Canceled,
          Error: new Error()
        };
  }
  return result;
}

export {
  Spinner ,
  Log ,
  Canceled ,
  resultOrRaise ,
}
/* @clack/prompts Not a pure module */
