// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NodePromisifiedMjs from "./NodePromisified.mjs";

var Promises = {};

var Fs = {
  Promises: Promises
};

var Path = {};

var Process = {};

var Url = {};

var Os = {};

function exec(prim) {
  return NodePromisifiedMjs.exec(prim);
}

var ChildProcess = {
  exec: exec
};

var Promisified = {
  ChildProcess: ChildProcess
};

export {
  Fs ,
  Path ,
  Process ,
  Url ,
  Os ,
  Promisified ,
}
/* ./NodePromisified.mjs Not a pure module */
