// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";

var dirname = Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url));

var packageJsonPath = Nodepath.join(dirname, "..", "package.json");

var templatesPath = Nodepath.join(dirname, "..", "templates");

function getTemplatePath(templateName) {
  return Nodepath.join(templatesPath, templateName);
}

export {
  packageJsonPath ,
  getTemplatePath ,
}
/* dirname Not a pure module */
