// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";

async function readJsonFile(filename) {
  return JSON.parse(await Nodefs.promises.readFile(filename, "utf8"));
}

async function updateFile(filename, updateFn) {
  var contents = await Nodefs.promises.readFile(filename, "utf8");
  var updated = updateFn(contents);
  return await Nodefs.promises.writeFile(filename, updated, "utf8");
}

function updateJsonFile(filename, updateFn) {
  return updateFile(filename, (function (contents) {
                var json = JSON.parse(contents);
                updateFn(json);
                return JSON.stringify(json, null, 2);
              }));
}

function getStringValue(json, fieldName) {
  if (!Array.isArray(json) && (json === null || typeof json !== "object") && typeof json !== "number" && typeof json !== "string" && typeof json !== "boolean") {
    return ;
  }
  if (!(typeof json === "object" && !Array.isArray(json))) {
    return ;
  }
  var match = json[fieldName];
  if (match !== undefined && !(!Array.isArray(match) && (match === null || typeof match !== "object") && typeof match !== "number" && typeof match !== "string" && typeof match !== "boolean" || typeof match !== "string")) {
    return match;
  }
  
}

export {
  readJsonFile ,
  updateJsonFile ,
  getStringValue ,
}
/* node:fs Not a pure module */
