// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var packageManagers = [
  "npm",
  "pnpm",
  "yarn",
  "bun"
];

function getActivePackageManager() {
  return Core__Option.getOr(Core__Option.flatMap(process.env.npm_execpath, (function (execpath) {
                    return packageManagers.find(function (pm) {
                                return execpath.includes(pm);
                              });
                  })), "npm");
}

export {
  getActivePackageManager ,
}
/* No side effect */
