// Generated by ReScript, PLEASE EDIT WITH CARE


var basicTemplateName = "rescript-template-basic";

var templates = [
  {
    name: "rescript-template-vite",
    displayName: "Vite",
    shortDescription: "Vite 5, React and Tailwind CSS"
  },
  {
    name: "rescript-template-nextjs",
    displayName: "Next.js",
    shortDescription: "Next.js 14 and Tailwind CSS"
  },
  {
    name: basicTemplateName,
    displayName: "Basic",
    shortDescription: "Command line hello world app"
  }
];

export {
  basicTemplateName ,
  templates ,
}
/* No side effect */
